<a href="https://colab.research.google.com/github/DavidUrbaez/AI_Course/blob/main/content/LAB%2002.04%20-%20CARD%20TRICK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 02.04 - Card trick

In [1]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()


replicating local resources


In [128]:
from local.lib.rlxmoocapi import submit, session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L02.04", varname="student");

logging in as durbaezl@unal.edu.co... please wait
using course session ai4eng.v1::open
success!! you are logged in


In [3]:
import numpy as np
import pandas as pd
import itertools

## Setup 

make sure to **watch the corresponding video** to understand the card trick.

### create a deck for a given configuration

The following function returns a list of **card names**. The `shuffle` argument is self evident. We use two letters as an arbitrary card name so that we have enough names for large configurations.

In [5]:

def create_deck(n_heaps, cards_per_heap, shuffle=False):
    n_cards = n_heaps * cards_per_heap
    
    chars = [chr(i) for i in np.arange(26)+65]
    names = [i+j for i,j in itertools.product(chars, chars)]    

    assert n_cards < len(names), "cannot have more than %d cards"%len(name)
    
    c = np.r_[names[:n_cards]]
    if shuffle:
        c = np.random.permutation(c)
    return c

In [6]:
create_deck(n_heaps=3, cards_per_heap=10, shuffle=False)

array(['AA', 'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AI', 'AJ', 'AK',
       'AL', 'AM', 'AN', 'AO', 'AP', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AV',
       'AW', 'AX', 'AY', 'AZ', 'BA', 'BB', 'BC', 'BD'], dtype='<U2')

In [7]:
create_deck(n_heaps=3, cards_per_heap=7, shuffle=True)

array(['AL', 'AA', 'AR', 'AD', 'AG', 'AQ', 'AM', 'AJ', 'AC', 'AT', 'AI',
       'AB', 'AS', 'AU', 'AF', 'AH', 'AN', 'AK', 'AE', 'AP', 'AO'],
      dtype='<U2')

In [8]:
create_deck(n_heaps=3, cards_per_heap=10, shuffle=True)

array(['AW', 'AK', 'AX', 'AY', 'AP', 'AZ', 'AV', 'AB', 'AA', 'BA', 'BB',
       'AC', 'BD', 'AF', 'AM', 'AS', 'BC', 'AG', 'AL', 'AR', 'AD', 'AN',
       'AU', 'AH', 'AQ', 'AO', 'AJ', 'AT', 'AI', 'AE'], dtype='<U2')

### pick a card

the following function randomly picks a card from a deck

In [9]:
def pick_card(c):
    return np.random.choice(c)

In [10]:
c = create_deck(n_heaps=3, cards_per_heap=7, shuffle=True)
n = pick_card(c)
n

'AM'

## Task 1. Make the heaps

Complete the following funcion so that given desk (as a list returned by `create_deck`) distributes the cards in `n_heaps` according to the procedure of the card trick shown in the video.

The heaps must be a list of `n_heaps` lists, each one with `len(c)/n_heaps` card names.

`n_heaps` will be an odd number (so that later we can put the chosen heap in the middle of the others), and must be a divisor of the total number of cards in the deck (so that all heaps have the same number of cards)

For instance, 

    >>> n_heaps = 3
    >>> c = create_deck(n_heaps=n_heaps, cards_per_heap=7)
    >>> h = make_heaps(c, n_heaps)
    >>> print("deck", c)
    >>> print("heaps")
    >>> h   

    deck ['AA' 'AB' 'AC' 'AD' 'AE' 'AF' 'AG' 'AH' 'AI' 'AJ' 'AK' 'AL' 'AM' 'AN'
     'AO' 'AP' 'AQ' 'AR' 'AS' 'AT' 'AU']
    heaps
    [['AA', 'AD', 'AG', 'AJ', 'AM', 'AP', 'AS'],
     ['AB', 'AE', 'AH', 'AK', 'AN', 'AQ', 'AT'],
     ['AC', 'AF', 'AI', 'AL', 'AO', 'AR', 'AU']]
  
or also

    >>> n_heaps = 5
    >>> c = create_deck(n_heaps=n_heaps, cards_per_heap=3, shuffle=True)
    >>> h = make_heaps(c, n_heaps)
    >>> print("deck", c)
    >>> print("heaps")
    >>> h
    
    deck ['AA' 'AJ' 'AM' 'AK' 'AH' 'AF' 'AD' 'AN' 'AB' 'AC' 'AG' 'AE' 'AL' 'AI'
     'AO']
    heaps
    [['AA', 'AF', 'AG'],
     ['AJ', 'AD', 'AE'],
     ['AM', 'AN', 'AL'],
     ['AK', 'AB', 'AI'],
     ['AH', 'AC', 'AO']]

In [11]:
def make_heaps(c, n_heaps=3):
    assert n_heaps%2==1, "must have an odd number of heaps"
    assert len(c)%n_heaps==0, "the length of the deck must be a multiple of the number of heaps"
    
    return [list(heap) for heap in c.reshape(n_heaps,-1,order='F')]

In [12]:
list(c.reshape(3,-1,order='F'))

[array(['AD', 'AT', 'AS', 'AQ', 'AI', 'AR', 'AG'], dtype='<U2'),
 array(['AF', 'AE', 'AC', 'AJ', 'AL', 'AP', 'AO'], dtype='<U2'),
 array(['AK', 'AN', 'AB', 'AM', 'AH', 'AA', 'AU'], dtype='<U2')]

manually check your code

In [13]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=7)
h = make_heaps(c, n_heaps)

print("deck", c)
print("heaps")
h


deck ['AA' 'AB' 'AC' 'AD' 'AE' 'AF' 'AG' 'AH' 'AI' 'AJ' 'AK' 'AL' 'AM' 'AN'
 'AO' 'AP' 'AQ' 'AR' 'AS' 'AT' 'AU']
heaps


[['AA', 'AD', 'AG', 'AJ', 'AM', 'AP', 'AS'],
 ['AB', 'AE', 'AH', 'AK', 'AN', 'AQ', 'AT'],
 ['AC', 'AF', 'AI', 'AL', 'AO', 'AR', 'AU']]

In [14]:
n_heaps = 5
c = create_deck(n_heaps=n_heaps, cards_per_heap=3, shuffle=True)
h = make_heaps(c, n_heaps)

print("deck", c)
print("heaps")
h


deck ['AI' 'AB' 'AH' 'AJ' 'AN' 'AC' 'AD' 'AF' 'AO' 'AE' 'AL' 'AA' 'AM' 'AG'
 'AK']
heaps


[['AI', 'AC', 'AL'],
 ['AB', 'AD', 'AA'],
 ['AH', 'AF', 'AM'],
 ['AJ', 'AO', 'AG'],
 ['AN', 'AE', 'AK']]

**submit your code**

In [15]:
student.submit_task(globals(), task_id="task_01");

## Task 2: Organize the heaps

Complete the following funcion so that given a set of heaps (such as the ones returned by the function of the previous task) and a card name:

1. Finds what is the heap that contains the card
1. Makes randomly two groups of `n_heaps//2` heaps of the remaining heaps
   - if `n_heaps=3` this will be two groups of one heap each, since `3//2=1`
   - if `n_heaps=5`, it will be two groups of two heaps each, since `5//2=2`
   - etc. (observe `//` is the integer division)
1. Concatenates the cards in one group with the cards in the heap containing the given card name. with the cards of the second group

For example

    >>> n_heaps = 3
    >>> c = create_deck(n_heaps=n_heaps, cards_per_heap=7, shuffle=True)
    >>> n = pick_card(c)
    >>> print ("card picked", n)
    >>> h = make_heaps(c, n_heaps)
    >>> h
    
    card picked AD
    [['AP', 'AC', 'AE', 'AO', 'AQ', 'AF', 'AM'],
     ['AN', 'AT', 'AB', 'AJ', 'AU', 'AI', 'AS'],
     ['AR', 'AD', 'AA', 'AG', 'AH', 'AL', 'AK']]
    
    
    >>> new_c = collect_heaps(h, n)
    >>> print (new_c)
    
    ['AP', 'AC', 'AE', 'AO', 'AQ', 'AF', 'AM', 'AR', 'AD', 'AA', 'AG', 'AH', 'AL', 'AK', 'AN', 'AT', 'AB', 'AJ', 'AU', 'AI', 'AS']

In [22]:
def collect_heaps(h, n):
    # print(n)
    r = [index for index, x in enumerate(h) if n in x][0]
    
    dis= len(h)//2

    other_heaps=h.copy()
    important_heap = other_heaps.pop(r)

    output =[]
    
    for index in range(dis):
      output = output + other_heaps[:dis][index]
    
    output= output+important_heap
    
    for index in range(dis):
      output = output + other_heaps[dis:][index]

    return output

manually check your code

In [17]:
n_heaps = 5
c = create_deck(n_heaps=n_heaps, cards_per_heap=7, shuffle=True)
n = pick_card(c)
print ("card picked", n)
h = make_heaps(c, n_heaps)
h

card picked AY


[['AV', 'AB', 'AO', 'AC', 'AK', 'BC', 'AT'],
 ['AZ', 'BF', 'AI', 'AE', 'BE', 'AL', 'BH'],
 ['AM', 'AF', 'BG', 'BI', 'AJ', 'AQ', 'AN'],
 ['AW', 'AP', 'AG', 'AR', 'AX', 'AH', 'AU'],
 ['AA', 'BD', 'BB', 'AS', 'AY', 'BA', 'AD']]

In [18]:
new_c = collect_heaps(h, n)
print (new_c)


AY
['AV', 'AB', 'AO', 'AC', 'AK', 'BC', 'AT', 'AZ', 'BF', 'AI', 'AE', 'BE', 'AL', 'BH', 'AA', 'BD', 'BB', 'AS', 'AY', 'BA', 'AD', 'AM', 'AF', 'BG', 'BI', 'AJ', 'AQ', 'AN', 'AW', 'AP', 'AG', 'AR', 'AX', 'AH', 'AU']


**submit your code**

In [19]:
student.submit_task(globals(), task_id="task_02");

## Task 3: Run the card trick

Complete the following function such that, when given a a deck of cards `c`, and picked card `n` and a number of heaps `n_heaps`, returns the position of the picked card after doing three times the collect. The position number **must start at zero**.

For instance:

- For `n_heaps=3` and `cards_per_heap=7`, the final position will always be 10 (which is 11 if you start counting at 1)
- For `n_heaps=3` and `cards_per_heap=4`, the final position will be sometimes 5 and sometimes 6 depending on the position of the picked card on the initial deck.
- For `n_heaps=5` and `cards_per_heap=3`, the final position will always be 7

**You must return an `int`**

In [51]:
def run(c, n, n_heaps=3):
    for _ in range(3):

      h = make_heaps(c, n_heaps)

      c = np.array(collect_heaps(h, n))

    return np.where(c == n)[0][0]
    # return c

manually check your code

In [100]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=7)
picked = "AA"
print ("desk", c)
pos = run(c, picked, n_heaps=n_heaps)
# pos
# list(pos).index(picked)
print ("position of card %s is %d"%(picked, pos))

desk ['AA' 'AB' 'AC' 'AD' 'AE' 'AF' 'AG' 'AH' 'AI' 'AJ' 'AK' 'AL' 'AM' 'AN'
 'AO' 'AP' 'AQ' 'AR' 'AS' 'AT' 'AU']
position of card AA is 10


In [99]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=4)
picked = "AI"
print ("deck", c)
pos = run(c, picked, n_heaps=n_heaps)
# pos
print ("position of card %s is %d"%(picked, pos))

deck ['AA' 'AB' 'AC' 'AD' 'AE' 'AF' 'AG' 'AH' 'AI' 'AJ' 'AK' 'AL']
position of card AI is 6


**submit your code**

In [54]:
student.submit_task(globals(), task_id="task_03");

In [101]:
def prev_run(c, n, n_heaps=3):
    out=[]
    for _ in range(3):

      h = make_heaps(c, n_heaps)

      c = np.array(collect_heaps(h, n))
      print(c)
      out.append(np.where(c == n)[0][0])

    return out
# picked
prev_run(c, picked, n_heaps=n_heaps)

['AB' 'AE' 'AH' 'AK' 'AN' 'AQ' 'AT' 'AA' 'AD' 'AG' 'AJ' 'AM' 'AP' 'AS'
 'AC' 'AF' 'AI' 'AL' 'AO' 'AR' 'AU']
['AB' 'AK' 'AT' 'AG' 'AP' 'AF' 'AO' 'AE' 'AN' 'AA' 'AJ' 'AS' 'AI' 'AR'
 'AH' 'AQ' 'AD' 'AM' 'AC' 'AL' 'AU']
['AK' 'AP' 'AE' 'AJ' 'AR' 'AD' 'AL' 'AB' 'AG' 'AO' 'AA' 'AI' 'AQ' 'AC'
 'AT' 'AF' 'AN' 'AS' 'AH' 'AM' 'AU']


[7, 9, 10]

array([[7]])

## Task 4: Run the trick using the math

Given:

- $n_h$: A number of heaps
- $c_h$: the number of cards per heap
- $i$: the position of a card 

The new position of the card after one cycle of making and collecting the heaps will be:

$$c_h(n_h\div2)+i\div n_h$$

Complete the following function so that it has the same functionality of the previous task, but applying only this formula without using the simulation above. You **MUST NOT ADD** or remove lines from the function skeleton below, **ONLY** fill in the `...`

You must get the same results as the previous task.

**HINT**: Use `np.argwhere` to get the initial position of the card in the deck

In [126]:
def mrun(c, picked_card, n_heaps=3):
    assert len(c)%n_heaps==0, "the number of heaps must be a divisor of the deck length"
    
    ch = len(c)//n_heaps # cards per heap
    nh = n_heaps
    
    i = np.argwhere(c==picked_card) # initial position of the card on the deck c
    p1 = ch * ( nh // 2) + (i) // nh  # the position of the card after the first round
    p2 = ch * ( nh // 2) + (p1) // nh   # the position of the card after the second round
    p3 =  ch * ( nh // 2) + (p2) // nh # the position of the card after the last round
    
    return p3
mrun(c, picked, n_heaps=n_heaps)

array([[10]])

In [58]:
x=np.array([1,2,3,4])
np.argwhere(x==2)

array([[1]])

In [72]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=4)
picked = "AI"
print ("deck", c)
pos = mrun(c, picked, n_heaps=n_heaps)
print ("position of card %s is %d"%(picked, pos))

deck ['AA' 'AB' 'AC' 'AD' 'AE' 'AF' 'AG' 'AH' 'AI' 'AJ' 'AK' 'AL']
position of card AI is 5


In [73]:
n=picked
h = make_heaps(c, n_heaps)

c = np.array(collect_heaps(h, n))

h = make_heaps(c, n_heaps)

c = np.array(collect_heaps(h, n))


array(['AD', 'AC', 'AL', 'AH', 'AA', 'AJ', 'AI', 'AE', 'AG', 'AF', 'AB',
       'AK'], dtype='<U2')

**submit your code**

In [129]:
student.submit_task(globals(), task_id="task_04");

## You are done. Now, some considerations

### using the math is always faster!!!



In [ ]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=4)
picked = "AI"
print ("deck", c)

In [ ]:
%timeit run(c, picked, n_heaps=n_heaps)

In [ ]:
%timeit mrun(c, picked, n_heaps=n_heaps)

### you can check if the trick works for a specific configuration

In [ ]:
n_heaps = 3
cards_per_heap = 7

c = create_deck(n_heaps, cards_per_heap)

r = [[n, mrun(c,n, n_heaps=n_heaps)] for n in c]
print ("deck", c)
pd.DataFrame(r, columns=["card picked", "final position"])

In [ ]:
n_heaps = 3
cards_per_heap = 4

c = create_deck(n_heaps, cards_per_heap)

r = [[n, mrun(c,n, n_heaps=n_heaps)] for n in c]
print ("deck", c)
pd.DataFrame(r, columns=["card picked", "final position"])